### ISSUE TITLE
"For Each...Next" statements are mistranslated as "ごとにしています...次へ"

### ISSUE THREAD

**Issue by nogic1008** [dotnet/dotnet-api-docs.ja-jp#98]
`For Each ... Next` is a VB.NET statement that should not be translated, but it is machine translated.

I found it in the following file:
- [System.Span\<T>.Enumerator](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/Span%601%2BEnumerator.xml)
- [System.ReadOnlySpan\<T>.Enumerator](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System/ReadOnlySpan%601%2BEnumerator.xml)
- [Microsoft.VisualBasic.Collection](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/Microsoft.VisualBasic/Collection.xml)

Since I searched from the [docs web site](https://docs.microsoft.com/ja-jp/search/index?search=%22%E3%81%94%E3%81%A8%E3%81%AB%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%22&scope=.NET), there may be other documents with this problem.

**Comment by CeciAc** [comment]
Hello, @nogic1008

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs.ja-jp/issues/709 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
